management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
