server:
  port: 8988
spring:
  application:
    name: service-hi-zipkin
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
